### PR TITLE
BLD: update for rc2

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
@ocefpaf I am optimistic about this so I merged it, I hope the bug with it being on the main channel is fixed!

**Comment by ocefpaf** [comment]
Probably not ; -)
But I will check them soon .

**Comment by flamingbear** [comment]
@tacaswell We just picked up an rc version from main, is that expected?

```
26 11:20:05 2015 from 172.18.235.30
vagrant@vmmushyseal:~$ conda list | grep matplot
matplotlib                2.0.0rc2            np111py35_0    conda-forge/channel/main
```

**Comment by ocefpaf** [comment]
Should be fixed now. I guess that the merge of #87 triggered that :unamused:

**Pull request merged**
