### PR TITLE
REL: version bump for 3.1.0rc1

### PR DESCRIPTION
**Pull request by tacaswell**
rerendered (which seems to have gotten rid of travis all together ?!)

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tacaswell** [comment]
Also a reminder that everytime we do this the tags get messed up and the RC ends up on the main channel for a bit ;)

**Comment by tacaswell** [comment]
It looks like these is an issue on azure where xwindows is not installed so importing tk fails:

```
import: 'matplotlib.backends._tkagg'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/matplotlib_1555726667024/test_tmp/run_test.py", line 29, in <module>
    import matplotlib.backends._tkagg
ImportError: libX11.so.6: cannot open shared object file: No such file or directory
```

**Comment by ocefpaf** [comment]
> Also a reminder that everytime we do this the tags get messed up and the RC ends up on the main channel for a bit ;)

We really need to update the docs on this. The previous method was just the extra label in the `conda-forge.yaml`. I have no idea  how is the "new way."

Pinging @conda-forge/core here and @croth1 (the doc wizard) for awareness.
(I can write the docs, just need to find out what if the new way of releasing dev versions.)

**Comment by croth1** [comment]
> It looks like these is an issue on azure where xwindows is not installed so importing tk fails:
> 
> ```
> import: 'matplotlib.backends._tkagg'
> Traceback (most recent call last):
>   File "/home/conda/feedstock_root/build_artifacts/matplotlib_1555726667024/test_tmp/run_test.py", line 29, in <module>
>     import matplotlib.backends._tkagg
> ImportError: libX11.so.6: cannot open shared object file: No such file or directory
> ```

Which reminds me that we still don't have docs on how to properly depend on X11 - we should probably add this to the documentation.

>We really need to update the docs on this. The previous method was just the extra label in the conda-forge.yaml. I have no idea how is the "new way."

I have no clue about labels. Maybe somebody of @conda-forge/core knows how this is done now?

Side note: To me it looks like the X11 and libGL dependencies in this feedstock may need updating. There's a libGL in yum_requirements.txt, but cdt packages are not used, as describe here: http://conda-forge.org/docs/maintainer/knowledge_base.html#libgl.

**Pull request merged**
