### PR TITLE
REL: bump for v2.1.2

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
fingers crossed I did this right on the first try this time!

**Comment by tacaswell** [comment]
nope, screwed up moving the branches, power-cycling to restart

**Comment by tacaswell** [comment]
I think the current sha is correct, but GH may take a while to decide it needs to re-generate the tarball.

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by ocefpaf** [comment]
@tacaswell Travis-CI is taking days to complete, so let's merge this to get the Linux and Windows packages up. I'll watch Travis-CI on `master` and fix it later if things are broken there.

**Pull request merged**
