### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by tacaswell**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tacaswell** [comment]
Not sure how to prevent CI from running on 2.7 so I assume those will just fail....

Are there instructions someplace about how to test these recipes locally?

**Comment by tacaswell** [comment]
So it's not trying to build 2.7 but is also not building 3.5....

**Comment by tacaswell** [comment]
I suspect that the re-rendering broke the rc channel upload...

**Comment by jakirkham** [comment]
> So it's not trying to build 2.7 but is also not building 3.5....

It may be there are some pinnings (e.g. `freetype`) that work with `pyqt` built only for Python 3.6 and not Python 3.5. Would require closer investigation to determine if this or some other pinning constraint causes the issue.

**Comment by tacaswell** [comment]
:tada: It passes!

In the interest of the RC tested, I would be happy to see this merged with just py36.

Someone who understands CF internals should check that it is still being uploaded to the correct place.

**Comment by ocefpaf** [comment]
> Someone who understands CF internals should check that it is still being uploaded to the correct place.

It will be uploaded to the `rc` channel.

**Comment by tacaswell** [comment]
Thanks @ocefpaf !

**Comment by dopplershift** [comment]
@msarahan Moved for me

**Comment by ocefpaf** [comment]
This is an old bug that I thought we fixed it :-/
Let me check that...

**Comment by CJ-Wright** [comment]
This is a new bug xref: https://github.com/conda-forge/conda-smithy/issues/886

**Comment by ocefpaf** [comment]
> This is a new bug xref: conda-forge/conda-smithy#886

Thanks for checking this our @CJ-Wright in a way it is a regression b/c that used to be the case. We need more tests...

**Pull request merged**
