### PR TITLE
Remove janschulz

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @janschulz.

(See https://github.com/conda-forge/matplotlib-feedstock/pull/16#issuecomment-217915913)

### CODE REVIEW

**Comment by janschulz** [comment]
Thanks! :-) Didn't expect that you start a new Build just for that...

**Comment by ocefpaf** [comment]
The build on `CircleCI` does not obey the `[skip ci]` directive. And I am not bumping the build number, so there is no actual build.

**Comment by janschulz** [comment]
https://circleci.com/docs/skip-a-build/ ?

**Comment by ocefpaf** [comment]
Read all the way to the bottom :wink: 

> Note that if the commits were in the opposite order, then the push would have been built. Currently neither [ci skip] nor [skip ci] supports fork PRs.

**Comment by janschulz** [comment]
Just put the `[skip CI]` into the merge message again?

**Pull request merged**
