### PR TITLE
TST: Ping CIs

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~~Bumped the build number (if the version is unchanged)~~
* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] ~~[Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)~~
* [x] Ensured the license file is being packaged.

If this is green we could merge it to see if it actually uploads 3.9.1, which would be nice.

Not updating the build number since there is no 3.9.1 build 0 currently. Not rerendering because that bumps to cos7 which seemed problematic in #390.

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
@conda-forge/help-python any idea about this error which seems to have appeared out of nowhere (before the rerender and after even though things had been green a couple of days ago):
```
WARNING (matplotlib-base): interpreted library (Python) package conda-forge/noarch::packaging==24.1=pyhd8ed1ab_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(execute())
  File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
    api.build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
    packages_from_this = build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2711, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 1850, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 1664, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/post.py", line 1728, in post_build
    check_overlinking(m, files, host_prefix)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/post.py", line 1553, in check_overlinking
    return check_overlinking_impl(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/post.py", line 1530, in check_overlinking_impl
    raise OverLinkingError(overlinking_errors)
conda_build.exceptions.OverLinkingError: overlinking check failed 
['  ERROR (matplotlib-base,lib/python3.9/site-packages/matplotlib/_qhull.pypy39-pp73-ppc_64-linux-gnu.so): $RPATH/ld64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (matplotlib-base,lib/python3.9/site-packages/matplotlib/_path.pypy39-pp73-ppc_64-linux-gnu.so): $RPATH/ld64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (matplotlib-base,lib/python3.9/site-packages/matplotlib/_tri.pypy39-pp73-ppc_64-linux-gnu.so): $RPATH/ld64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (matplotlib-base,lib/python3.9/site-packages/matplotlib/_image.pypy39-pp73-ppc_64-linux-gnu.so): $RPATH/ld64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (matplotlib-base,lib/python3.9/site-packages/matplotlib/backends/_tkagg.pypy39-pp73-ppc_64-linux-gnu.so): $RPATH/ld64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?']
```

**Comment by isuruf** [comment]
Can you open an issue in github.com/conda/conda-build ?

**Comment by h-vetinari** [comment]
> Can you open an issue in github.com/conda/conda-build ?

I think this is somehow sysroot related: https://github.com/conda-forge/linux-sysroot-feedstock/issues/67

**Comment by h-vetinari** [comment]
OK, I've opened the issue & fixed ppc in #396 (without doing the cos7 bump for linux-64 yet).

**Pull request closed without merging**
