### PR TITLE
Add msvc_runtime dependency

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://github.com/conda-forge/matplotlib-feedstock/issues/1#issuecomment-217853620

If I got it right most of the changes suggested in https://github.com/conda-forge/matplotlib-feedstock/issues/1#issuecomment-217853620 cannot be implemented until we get a new matplolib release.

### CODE REVIEW

**Comment by janschulz** [comment]
No, the most important is the bld.bat one and that's independent of the upstream changes in setup.py/setupext.py. Only the dropping of the patches are dependent on a new upstream version (and only partly,as even the upstream versions sets some default backends).

```
diff -u -w -B "..\\matplotlib-feedstock\\recipe/bld.bat" "ci\\conda_recipe/bld.bat"
--- "..\\matplotlib-feedstock\\recipe/bld.bat"  2016-01-23 17:17:26.462108000 +0100
+++ "ci\\conda_recipe/bld.bat"  2016-02-06 20:36:22.080285800 +0100
@@ -1,6 +1,5 @@
-set LIB=%LIBRARY_LIB%
 set LIBPATH=%LIBRARY_LIB%;
-set INCLUDE=%LIBRARY_INC%;%PREFIX%\Library\include\freetype2
+set INCLUDE=%INCLUDE%;%PREFIX%\Library\include\freetype2

 ECHO [directories] > setup.cfg
 ECHO basedirlist = %LIBRARY_PREFIX% >> setup.cfg
@@ -9,5 +8,5 @@
 ECHO sample_data = False >> setup.cfg
 ECHO toolkits_tests = False >> setup.cfg

-python setup.py install
+%PYTHON% setup.py install
 if errorlevel 1 exit 1
```

**Comment by ocefpaf** [comment]
What sets `%INCLUDE%` and why not `%LIBRARY_INC%`? The former is not set  in the `bld.bat` until that line and the latter **is** the conda directory for it. I do not understand that change.

**Comment by janschulz** [comment]
INCLUDE is AFAIK set by conda-build: https://github.com/conda/conda-build/blob/c6b9aba7c318b49b298399e1d491ee93a937ef1d/conda_build/windows.py#L195
-> The real executed bld.bat ends up calling vcsargsall and setting some variables. INCLUDE in the end contains LIBRARY_INC: https://github.com/conda/conda-build/blob/c6b9aba7c318b49b298399e1d491ee93a937ef1d/conda_build/windows.py#L203

**Comment by ocefpaf** [comment]
Thanks! That is confusing. Anyways, if I got that right that last line will create a `INCLUDE` env var on Windows that already has `LIBRARY_INC`, so that is redundant, right? Not sure if we need the `%INCLUDE%`, but it does not hurt to add it.

**Comment by janschulz** [comment]
Yes, thats what I think too. But matplotlibs [appveyor config](https://github.com/matplotlib/matplotlib/blob/master/appveyor.yml) does not contain any INCLUDE, so that should be fine.

conda doesn't seem to set it:
```
λ grep -R INCLUDE
CHANGELOG.txt:  * removing LIBRARY_PATH and INCLUDE_PATH build environment variables on
CHANGELOG.txt:  * set LIBRARY_PATH and INCLUDE_PATH when building on Unix
conda_build/environ.py:            'LUA_INCLUDE_DIR': get_lua_include_dir(),
conda_build/windows.py:            fo.write("set INCLUDE={};%INCLUDE%\n".format(env["LIBRARY_INC"]))
```

**Comment by janschulz** [comment]
The main thing here is `python`-> `%PYTHON%` because somehow the first python in path was wrong.

**Comment by ocefpaf** [comment]
After lots of test none of the changes here seemed important nor they fixed the build. The renaming build issue (#1) can only be fixed by the [`vcvars64.bat`](https://github.com/janschulz/matplotlib/commit/63db4decca2501265db0f7b4ffae8147894776a1) workaround. I am reluctant to add that to the `appveyor.yml` as I believe that issue is currently being addressed in the latest conda-build. So I guess we need to wait for that.

**Comment by janschulz** [comment]
BTW: https://github.com/conda/conda-build/issues/729

**Pull request closed without merging**
