### PR TITLE
MNT: update for 1.5.2

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by ocefpaf** [comment]
OS X is failing to apply the [osx-tk.patch](https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/osx-tk.patch) patch. I tried to refresh the patch, but it seems that a lot has changed in `setupext.py`. I wonder if the patch is still needed.

**Comment by tacaswell** [comment]
The tk stuff got completely re done. I have a vague memory of going through
fixing this on the devel branch.

**Comment by ocefpaf** [comment]
> The tk stuff got completely re done. I have a vague memory of going through
fixing this on the devel branch.

Let's try to just remove those two patches.

PS: I will take a better look later today or early tomorrow to check if we still need to point the setup to `sys.prefix` to ensure matplotlib gets the conda version of those libs/headers.

**Comment by tacaswell** [comment]
cherry-picked the patch related commits off of the devel branch and rebased
on current master.

**Comment by ocefpaf** [comment]
LGTM!

**Pull request merged**
