### PR TITLE
Manual migration for PyPy windows

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The migrations dependency resolver ignored the selector on pyqt, and is waiting for pyqt (which will not work on PyPy), so try this manually.

I did not update the build number since this is a migration.

### CODE REVIEW

**Comment by mattip** [comment]
Hit a [build error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=360728&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba&l=1606) in _c_internal_utils.c in `return PyErr_SetFromWindowsErr(hr);`
```
src/_c_internal_utils.c(71): error C2440: 'return': cannot convert from 'void' to 'PyObject *'
```

PyPy doesnt' [do this right](https://foss.heptapod.net/pypy/pypy/-/blob/release-pypy3.7-v7.3.5/pypy/module/cpyext/pyerrors.py#L67). Patch needed.

**Comment by mattip** [comment]
It seems some other package is not available yet? I am not sure which one.

**Comment by mattip** [comment]
Close/reopen to restart CI

**Comment by mattip** [comment]
CI is passing.

**Comment by mattip** [comment]
Thanks!

**Comment by mattip** [comment]
This is still marked on the PyPy windows migration as "waiting for parents" @isuruf  is that blocking anything, and if so is there a way around it?

**Comment by isuruf** [comment]
cc @conda-forge/bot

**Comment by mattip** [comment]
I still see this as "waiting for parents" on the PyPy windows migration, even though this PR was merged. Is there a way around that?

**Comment by mattip** [comment]
Hmm. The migration bot still does not recognize matplotlib as updated.

**Comment by dopplershift** [comment]
@mattip Just to be clear, this is last year's issue. Probably meant #322.

**Comment by mattip** [comment]
Thanks for the correction, yes I meant #322. The PRs were similarly named, sorry for the confusion. In any case any ideas how to convince the migration bot that this package is available for pypy3.8/3.9?

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/matplotlib-feedstock/pull/322#issuecomment-1205758221

**Pull request merged**
