### PR TITLE
Bump testing

### PR DESCRIPTION
**Pull request by dopplershift**
Merge in the fixes on the master 3.0.2 branch. 

This is picking up a lot of commits because I've actually merged master into the testing branch. This should make future bumps a lot easier to deal with (I hope).

### CODE REVIEW

**Comment by dopplershift** [comment]
@ocefpaf Any additions I should make here to have the built packages *automatically* put up to conda-forge/label/testing?

**Comment by ocefpaf** [comment]
> @ocefpaf Any additions I should make here to have the built packages _automatically_ put up to conda-forge/label/testing?

In the past just adding

```yaml
channels:
  targets:
    - [conda-forge, testing]
```

to the `conda-forge.yml` and re-render would be enough. I'm not sure if that still works after all the changes done to accommodate the migration and multiple compilers. Pinging @mariusvniekerk who probably knows about it.

**Comment by dopplershift** [comment]
Adding your lines to `conda-forge.yml` and re-rendering did absolutely nothing, so that's not it.

I have what looks like the right incantation in `conda_build_config.yaml`, but that didn't produce the desired results last time...

**Comment by ocefpaf** [comment]
> Adding your lines to `conda-forge.yml` and re-rendering did absolutely nothing, so that's not it.
> 
> I have what looks like the right incantation in `conda_build_config.yaml`, but that didn't produce the desired results last time...

Yeah. Things changed and I did not keep track of it. @mariusvniekerk probably knows but I believe he is busy at the moment.

**Comment by dopplershift** [comment]
Ok, so my problem was that `conda_build_config.yaml` needs to be in the `recipe` directory, not in the repository root. New problem when I try to rerender using this config file:
```yaml
channel_targets:
  - conda-forge testing
  - conda-forge testing7  # [(linux or osx)     and (environ.get('CF_COMPILER_STACK') == 'comp7')]
```
I get this error:
```
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Adding in variants from /Users/rmay/miniconda3/conda_build_config.yaml
Adding in variants from /Users/rmay/repos/matplotlib-feedstock/recipe/conda_build_config.yaml
Traceback (most recent call last):
  File "/Users/rmay/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 278, in main
    args.subcommand_func(args)
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 186, in __call__
    exclusive_config_file=args.exclusive_config_file)
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 994, in main
    render_circle(env, config, forge_dir)
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 661, in render_circle
    extra_platform_files=extra_platform_files)
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 430, in _render_ci_provider
    channel_urls=forge_config.get('channels', {}).get('sources', []))
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 44, in render
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 766, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_build/variants.py", line 507, in get_package_variants
    combined_spec, extend_keys = combine_specs(specs, log_output=config.verbose)
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_build/variants.py", line 267, in combine_specs
    log_output=log_output)
  File "/Users/rmay/miniconda3/lib/python3.6/site-packages/conda_build/variants.py", line 242, in _combine_spec_dictionaries
    spec_source))
ValueError: variant config in /Users/rmay/repos/matplotlib-feedstock/recipe/conda_build_config.yaml is ambiguous because it does not fully implement all zipped keys, or specifies a subspace that is not fully implemented.
```

**Pull request merged**
