### PR TITLE
Update testing

### PR DESCRIPTION
**Pull request by dopplershift**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Just merged master in, so I don't want to rerender. I'd rather just merge in any re-rendering in the future from master to make continued merging simpler.

### CODE REVIEW

**Comment by dopplershift** [comment]
@ocefpaf Any idea if there's some way to make VS 2010 work for these Azure builds? Apparently, that's needed to build Matplotlib's fixed freetype 2.6.1.

**Comment by ocefpaf** [comment]
The very first `freetype` in `conda-forge` was `2.6.3` and I guess that, to make this testing branch consistent, we should build `2.6.1` with the new compilers, etc. This can be a can of worms depending on the dependencies. Let me try...

**Comment by ocefpaf** [comment]
@dopplershift, before I dive into this rabbit hole do, you mean `freetype 2.9.1` instead of `2.6.1`?

**Comment by dopplershift** [comment]
No, matplotlib has the option to build against a copy of freetype 2.6.1 that it downloads and builds within `setupext.py`--that's what this special branch does. This is to keep image-based tests passing, since freetype versions frequently result in pixel level changes in images.

**Comment by ocefpaf** [comment]
> No, matplotlib has the option to build against a copy of freetype 2.6.1 that it downloads and builds within `setupext.py`--that's what this special branch does. This is to keep image-based tests passing, since freetype versions frequently result in pixel level changes in images.

Let me see if I can get a `2.6.1` build going then...

**Comment by dopplershift** [comment]
Ok, so it seems AppVeyor is going to be our only way of doing windows builds with freetype 2.6.1. Any way to disable Azure windows builds or mark them expected fail?

**Comment by ocefpaf** [comment]
> Ok, so it seems AppVeyor is going to be our only way of doing windows builds with freetype 2.6.1. Any way to disable Azure windows builds or mark them expected fail?

You don't need to worry about the Azure failures here. AppVeyor is still our official Windows builder. If that is OK for you this is good to be merged.

(Actually, let me push something to this branch before you merge it, hold on...)

**Comment by dopplershift** [comment]
Ok, merging over azure for windows.

**Pull request merged**
