### PR TITLE
Bump to 3.8.0rc1

### PR DESCRIPTION
**Pull request by dopplershift**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dopplershift** [comment]
@ocefpaf I'm not sure why after a re-render this is still trying to build Python 3.8 since I'm explicitly asking to skip <3.9...do you see anything obvious I missed here?

**Comment by tacaswell** [comment]
It looks like the jobs are running, but do nothing.

**Comment by ocefpaf** [comment]
I wonder if we need a skip at the top level of the recipe to eliminate that from the CI. Like @tacaswell mentioned, the skip will ensure that nothing is built but that sure waste some CI time.

**Comment by dopplershift** [comment]
Right, I figured it wasn't doing anything, but would still prefer not to have the jobs at all. Unfortunately, at least running `conda smithy rerender` locally, even adding a top-level
```yaml
build:
  skip: true  # [py<39]
```
isn't triggering any changes.

**Comment by ocefpaf** [comment]
That most likely a bug in conda-smithy then. @isuruf, any ideas for us here?

**Comment by dopplershift** [comment]
I'm tempted to go ahead and merge and fix later if someone is motivated.

**Pull request merged**
