### PR TITLE
ENH: Re-enable the macosx backend.

### PR DESCRIPTION
**Pull request by dopplershift**
This worked locally for me on 10.12.1. Let's see what happens here...

### CODE REVIEW

**Comment by dopplershift** [comment]
No idea what exactly to do about the license lint.

**Comment by ocefpaf** [comment]
Just ignore that. It was a bad change to the linter. The word license
should not be blacklisted.

**********************************************************
Filipe P. A. Fernandes
Physical Oceanographer

Email: ocefpaf@gmail.com

http://ocefpaf.github.io/
**********************************************************

**Comment by dopplershift** [comment]
@conda-froge/core @msarahan Is there any way to make the import tests for the recipe use `pythonw` rather than `python`--or any other way to use the mac "framework" version of python?

**Comment by msarahan** [comment]
Not directly in the import tests.  You can create run_test.sh though, and put

```
pythonw -c "import matplotlib"
```

in there.

**Comment by dopplershift** [comment]
I'm guessing that would need to be surrounded in a `if "Darwin"`-type block.

**Comment by msarahan** [comment]
Sure, if you must.  It will run that script on Linux and Mac - so if it's going to break linux for any reason, yeah, add that block.

**Comment by dopplershift** [comment]
I didn't think `pythonw` was a thing on linux...

**Comment by dopplershift** [comment]
@conda-forge/matplotlib This is passing--any feedback here? It would be nice to get packages with the osx backend enabled.

**Comment by dopplershift** [comment]
Just FYI--One of you guys will have to merge, as I can't. :grin:

**Comment by ocefpaf** [comment]
It sucks to merge 'failing' PR over the phone because GitHub requires you to switch to desktop mode.

PS: that linter 'improvement' should go.

**Comment by amelio-vazquez-reina** [comment]
Sorry to jump on this thread without enough context, but after upgrading matplotlib to the latest version on `conda-forge` just today, I run into problems precisely with this line

```
---> 24 from matplotlib.backends import _macosx
```

I posted an issue here: https://github.com/matplotlib/matplotlib/issues/7709
, but I now realize this was probably a better place for it.

**Comment by dopplershift** [comment]
Does using `pythonw` instead of `python` make it work?

**Comment by amelio-vazquez-reina** [comment]
Thanks, yes `pythonw` makes it work

```
$ python -c "from matplotlib.backends import _macosx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

$ pythonw -c "from matplotlib.backends import _macosx"
$
```

**Comment by amelio-vazquez-reina** [comment]
When I try in IPython:

`ipython --pylab=osx`

it still fails with the same error.

**Pull request merged**
