### PR TITLE
Update to v.3.8.0 Numpy version fix

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@dopplershift 
This includes a minor change to the recipe to match the source repo setup.p7
https://github.com/matplotlib/matplotlib/blob/v3.8.0/setup.py#L336
        "numpy>=1.21,<2",
Recipe changed to reflect setup.py

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by dopplershift** [comment]
I'm about to put one up that merges in the changes that were done for the RC. I'd prefer that route since it makes keeping all these things in sync easier.

**Comment by dopplershift** [comment]
I'll pull in you numpy change if it's not already there.

**Comment by rxm7706** [comment]
Closing - in favor of - 

> I'm about to put one up that merges in the changes that were done for the RC. I'd prefer that route since it makes keeping all these things in sync easier.

**Pull request closed without merging**
