### PR TITLE
Enable aarch64 and ppc64le builds

### PR DESCRIPTION
**Pull request by jjhelmus**
The arch migrator is waiting for pyqt to be build for these platforms but this is unnecessary if a different backend, such as tk, is used on these platforms.
  
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
This was fixed in conda-smithy. Need a rerender and a merge conflict resolve

**Comment by dopplershift** [comment]
@conda-forge-admin please rerender

**Comment by dopplershift** [comment]
Well, it was worth a shot. 😁

**Comment by hadim** [comment]
Please see https://github.com/conda-forge/matplotlib-feedstock/pull/223

**Comment by dopplershift** [comment]
Superseded by #223 .

**Pull request closed without merging**
