### PR TITLE
WIP: Testing the conda-build beta

### PR DESCRIPTION
**Pull request by ocefpaf**
**Do not merge!** Just testing...

### CODE REVIEW

**Comment by ocefpaf** [comment]
`conda-build 1.20.2_beta-py27_0` is a no go :unamused: 

Same as https://github.com/conda-forge/apptools-feedstock/pull/2#issuecomment-217778646

**Comment by janschulz** [comment]
I don't see an error (seems that the , but meta.yml is only specifying functools in ru, not build. Could it be that?

**Comment by janschulz** [comment]
Sorry, pressend wrong button :-( [wanted to cance my comment, not the PR]

**Comment by ocefpaf** [comment]
I cancelled b/c it is an issue with `conda-build`. It cannot shake off a `conda lock` that appears for an unknown reason.

**Comment by janschulz** [comment]
BTW: can you remove me from the maintainer list here? I'm happy to be subscribed to this feedstock, but I don't want to have any official responsibility here and without having admin rights here, I can't break something :-)

**Comment by ocefpaf** [comment]
> BTW: can you remove me from the maintainer list here? I'm happy to be subscribed to this feedstock, but I don't want to have any official responsibility here and without having admin rights here, I can't break something :-)

Sure. Sad to see you go. I still need to catch up with the canonical recipe and your help tere would be very valuable.

**Pull request closed without merging**
