### PR TITLE
BLD: update for version 2.0.0rc1

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
help @pelson @ericdill 

I seem to break something everytime I have tried to do this 😞

**Comment by tacaswell** [comment]
from appveyor:

```
Executing: conda build recipe --quiet
Error: 'numpy x.x' requires external setting
Command exited with code 1
```

I assume this means some setting is missing to know about the numpy matrix?

**Comment by tacaswell** [comment]
Looks like I got travis and circle running again, but not appveyor :/

**Comment by jakirkham** [comment]
Guessing this can be closed out now.

**Pull request closed without merging**
