### PR TITLE
ENH: Support Python 3.11

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Just a naive attempt at adding 3.11 support via `.ci_support/migrations`. Feel free to close if you know it won't work or someone else is already working on this.

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please restart ci

**Comment by tacaswell** [comment]
Segfaults in the py39 osx arm64 build 😱 

```
/Users/runner/miniforge3/etc/profile.d/conda.sh: line 23:  5462 Segmentation fault: 11  ( "$CONDA_EXE" $_CE_M $_CE_CONDA "$@" )

```

Given that the point here is to add py311 can we merge despite that issue?

**Comment by jakirkham** [comment]
The segfault is a known issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1823 ) and usually goes away on restarting the job (though agree it needs work)

That said, only see 2 failures above from Python 3.11. Am I missing something?

**Comment by jakirkham** [comment]
Restarting the failed job. Hopefully should it clear it up

**Comment by larsoner** [comment]
Green!

**Pull request merged**
