### PR TITLE
Build on Windows

### LINKED ISSUE #11: Matplotlib is greyed-out on AppVeyor
appv

Is that correct? Are we not building matplotlib o Windows?

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #11

### CODE REVIEW

**Comment by pelson** [comment]
:+1: if this passes.

**Comment by ocefpaf** [comment]
Looks like Win64 is still failing.

```shell
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IC:\conda\envs\_build\lib\site-packages\numpy\core\include -IC:\conda\envs\_build\Library\include -I. -IC:\conda\envs\_build\Library\include/freetype2 -IC:\conda\envs\_build\include -IC:\conda\envs\_build\PC /Tpsrc/ft2font.cpp /Fobuild\temp.win-amd64-2.7\Release\src/ft2font.obj
ft2font.cpp
src/ft2font.cpp(5) : fatal error C1083: Cannot open include file: 'string': No such file or directory 
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
 
C:\conda\conda-bld\work\matplotlib-1.5.1>if errorlevel 1 exit 1 
Command failed: C:\windows\system32\cmd.exe /c call bld.bat
```

**Comment by pelson** [comment]
FWIW same issue as #1

**Comment by ocefpaf** [comment]
Closing in favor of #15

**Pull request closed without merging**
