### PR TITLE
remove links

### LINKED ISSUE #214: Remove tcl, tk symlinks after the build
Otherwise they get packaged too.

### PR DESCRIPTION
**Pull request by ocefpaf**
@isuruf this fixes #214 but I don't recall why we needed that in the first place. Can you take a look and check if this covers what you want?

### CODE REVIEW

**Comment by isuruf** [comment]
#214 was about deleting these symlinks at the end of the build script, but if they are not needed at all during the build, removing them make more sense.

**Comment by ocefpaf** [comment]
> #214 was about deleting these symlinks at the end of the build script, but if they are not needed at all during the build, removing them make more sense.

Yeah. I tested that locally first before trying to remove the lines. But, b/c it passed when I removed the lines on Linux, I guess it was worth sending PR without them.

**Comment by ocefpaf** [comment]
Don't merge this yet. It looks like #230 broke GUI installs and I'm investigating how to fix it.

**Comment by tacaswell** [comment]
It looks like those lines have been there from f6c463ba391420cc4ce764735040c04f77afe49b  Given that I think mpl was one of the first packages that Phil did, it is likely they are fixes for problem that conda/conda-forge have solved in more global ways sense.

**Comment by ocefpaf** [comment]
> It looks like those lines have been there from [f6c463b](https://github.com/conda-forge/matplotlib-feedstock/commit/f6c463ba391420cc4ce764735040c04f77afe49b) Given that I think mpl was one of the first packages that Phil did, it is likely they are fixes for problem that conda/conda-forge have solved in more global ways sense.

Yeah, they have been there forever. But the real real they exist is probably lost to us b/c this recipe was ported [from conda-recipes](https://github.com/conda-forge/matplotlib-feedstock/commit/f6c463ba391420cc4ce764735040c04f77afe49b#diff-e178b687b10a71a3348107ae3154e44cR1) and maybe we never really needed that.

**Pull request merged**
