### PR TITLE
Pin pyqt (qt)

### PR DESCRIPTION
**Pull request by ocefpaf**
Helps with #60

### CODE REVIEW

**Comment by ocefpaf** [comment]
@tacaswell and @pelson any objections to merge this? It is hurting a not of Windows recipes like https://github.com/conda-forge/staged-recipes/pull/1705#issuecomment-251651274

**Comment by tacaswell** [comment]
I am :+1: on this until qt4/qt5 issues get sorted out.  I am not 100% that this will actually help though, as both builds will be floating around and the resolver could take either.

**Comment by ocefpaf** [comment]
> I am not 100% that this will actually help though, as both builds will be floating around and the resolver could take either.

In theory the solver should respect the pinning and get only `pyqt 4.11.*`.  And, since `pyqt` is pinned to `qt 4.8.*`, this "should" be enough. I will re-start AppVeyor on my failing builds as soon as the new binaries lands on the channel and let you know if it worked.

**Comment by tacaswell** [comment]
I meant there is still a build of mpl _without_ this pinning so the resolver can do qt5 and that version or qt4 and this version.

**Comment by ocefpaf** [comment]
> I meant there is still a build of mpl without this pinning so the resolver can do qt5 and that version or qt4 and this version.

The higher build number should take care of that. But we will have to wait to test this as AppVeyor is overwhelmed with all the unnecessary re-builds to fix an `OS X` issue on `Travis-CI` :unamused:

**Pull request merged**
