### PR TITLE
BLD: enforce cycler minimum version

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by janschulz** [comment]
Needs a built number increment

**Comment by pelson** [comment]
Are you seeing broken installations, or are you just being correct with the metadata. If the former, we can remove the builds from the conda-forge channel.

**Comment by tacaswell** [comment]
had the build number bump done, but uncommitted, force-pushed

@jreback had failures on OSX

**Comment by janschulz** [comment]
@pelson Just saw it when I looked at the changes :-)

**Comment by tacaswell** [comment]
Is this good to merge?

**Comment by ocefpaf** [comment]
LGTM

**Pull request merged**
