### PR TITLE
manually start PyPy migration

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The dependency resolver bot did not start the pypy3.8/3.9 migration because pyqt is a parent in the graph. But I think pyqt is an optional dependency, not a hard one. The PR works around the problem by manually adding the migration file.

### CODE REVIEW

**Comment by mattip** [comment]
For some reason CI did not start.

@conda-forge-admin please restart ci

**Review by dopplershift — APPROVED** [review]

**Comment by mattip** [comment]
Thanks!

**Comment by jakirkham** [comment]
Thanks Matti and Ryan! 🙏

**Comment by mattip** [comment]
This package is now available, but the migration bot doesn't seem to have picked it up. `matplotlib` is still at the top of the "awaiting parents" group on the [pypy3.8 migration](https://conda-forge.org/status/#pypy38). Is there a way to tell the bot that this migration is finished?

**Comment by jakirkham** [comment]
cc @conda-forge/bot

**Comment by jakirkham** [comment]
Surfaced the discussion here [on Gitter]( https://gitter.im/conda-forge/regro-cf-autotick-bot?at=62ec29e4d020d223d32dd68c ).

**Comment by mattip** [comment]
Still no movement, migration of the package seems in limbo.

**Comment by jakirkham** [comment]
Would just raise it in the meeting this week

**Comment by chrisburr** [comment]
I think it's because `pyqt` isn't migrated so it's not even considering `matplotlib` yet. Either that PR should be fixed or we can probably edit the bot metadata directly.

I think this would involve adding a section like:


* https://github.com/regro/cf-graph-countyfair/blob/3f7e9f2e22a8be6b0a9af6462555c2eab3a56f9c/node_attrs/numpy.json#L889-L907

to:

* https://github.com/regro/cf-graph-countyfair/blob/3f7e9f2e22a8be6b0a9af6462555c2eab3a56f9c/node_attrs/matplotlib.json

I'll try to take a look this morning.

**Comment by chrisburr** [comment]
Actually I found the proper fix that matches how this has been done for pypy37: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3326

**Comment by mattip** [comment]
Great, the migration seems unstuck now.

**Comment by jakirkham** [comment]
Thanks Chris! 🙏

Maybe we should document this for future reference. Matti, would you be willing to add this to the docs?

**Comment by mattip** [comment]
> the docs

Sure, where in the docs would be appropriate?

**Pull request merged**
