### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #290.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by ericpre** [comment]
This PR was to check if the missing linux config file issue in #289 wasn't a hiccup and it doesn't seem to be the case since rerendering doesn't add the linux CI config files back! There is something wrong somewhere.

**Comment by ocefpaf** [comment]
The skip statement is probably the cause. I'll check it later today.

**Comment by ericpre** [comment]
Ok, thanks!

**Comment by ocefpaf** [comment]
Fixed in #292

**Pull request closed without merging**
