### PR TITLE
Update pinning

### PR DESCRIPTION
**Pull request by ocefpaf**
For the `numpy` matrix see conda-forge/conda-forge.github.io#415

### CODE REVIEW

**Comment by asmeurer** [comment]
I now get errors in OS X Travis CI:

```
  /Users/travis/miniconda/envs/test-environment/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
```

I believe it is coming from matplotlib.

According to https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility it means that matplotlib is compiled against the wrong numpy version. So I think this was the wrong change.

**Comment by ocefpaf** [comment]
Can you post the results of conda list?

**Comment by asmeurer** [comment]
Here's what got installed 

```
Package plan for installation in environment /Users/travis/miniconda/envs/test-environment:
The following NEW packages will be INSTALLED:
    ca-certificates: 2017.7.27.1-0      conda-forge
    catimg:          1.1.1-py35_0       conda-forge
    certifi:         2017.7.27.1-py35_0 conda-forge
    chardet:         3.0.2-py35_1       conda-forge
    cycler:          0.10.0-py35_0      conda-forge
    fastcache:       1.0.2-py35_0       conda-forge
    freetype:        2.7-1              conda-forge
    gmp:             6.1.2-0            conda-forge
    gmpy2:           2.0.8-py35_1       conda-forge
    idna:            2.5-py35_0         conda-forge
    imgurpython:     1.1.7-py35_0       conda-forge
    iterm2-tools:    2.3-py35_0         conda-forge
    jedi:            0.10.2-py35_0      conda-forge
    libpng:          1.6.28-0           conda-forge
    matplotlib:      2.0.2-py35_2       conda-forge
    mkl:             2017.0.3-0                    
    mpc:             1.0.3-4            conda-forge
    mpfr:            3.1.5-0            conda-forge
    mpmath:          0.19-py35_2        conda-forge
    ncurses:         5.9-10             conda-forge
    numpy:           1.13.1-py35_0                 
    openssl:         1.0.2l-0           conda-forge
    pandas:          0.20.3-py35_1      conda-forge
    patsy:           0.4.1-py35_0       conda-forge
    pip:             9.0.1-py35_0       conda-forge
    prompt_toolkit:  1.0.15-py35_0      conda-forge
    py:              1.4.34-py35_0      conda-forge
    pyflakes:        1.6.0-py35_0       conda-forge
    pygments:        2.2.0-py35_0       conda-forge
    pyparsing:       2.2.0-py35_0       conda-forge
    pytest:          3.2.0-py35_0       conda-forge
    python:          3.5.4-0            conda-forge
    python-dateutil: 2.6.1-py35_0       conda-forge
    pytz:            2017.2-py35_0      conda-forge
    readline:        6.2-0              conda-forge
    requests:        2.18.3-py35_0      conda-forge
    scipy:           0.19.1-np113py35_0            
    seaborn:         0.8.0-py35_0       conda-forge
    setuptools:      36.2.2-py35_0      conda-forge
    six:             1.10.0-py35_1      conda-forge
    sqlite:          3.13.0-1           conda-forge
    statsmodels:     0.8.0-np113py35_0  conda-forge
    sympy:           1.1.1-py35_0       conda-forge
    tk:              8.5.19-2           conda-forge
    tornado:         4.5.1-py35_0       conda-forge
    urllib3:         1.21.1-py35_0      conda-forge
    wcwidth:         0.1.7-py35_0       conda-forge
    wheel:           0.29.0-py35_0      conda-forge
    xz:              5.2.2-0            conda-forge
    zlib:            1.2.11-0           conda-forge
```

**Comment by ocefpaf** [comment]
That version of mpl was built with `numpy 1.9.*` and you are running with `numpy 1.13.1`. That should be OK and I cannot reproduce the error on my Linux machine with the same packages:

```
Package plan for installation in environment /home/filipe/miniconda3/envs/TEST:

The following NEW packages will be INSTALLED:

    ca-certificates:  2017.7.27.1-0      conda-forge
    certifi:          2017.7.27.1-py35_0 conda-forge
    cycler:           0.10.0-py35_0      conda-forge
    dbus:             1.10.10-3          conda-forge
    expat:            2.2.1-0            conda-forge
    fontconfig:       2.12.1-4           conda-forge
    freetype:         2.7-1              conda-forge
    gettext:          0.19.7-1           conda-forge
    glib:             2.51.4-0           conda-forge
    gst-plugins-base: 1.8.0-0            conda-forge
    gstreamer:        1.8.0-2            conda-forge
    icu:              58.1-1             conda-forge
    jpeg:             9b-0               conda-forge
    libffi:           3.2.1-3            conda-forge
    libiconv:         1.14-4             conda-forge
    libpng:           1.6.28-0           conda-forge
    libxcb:           1.12-1             conda-forge
    libxml2:          2.9.4-4            conda-forge
    matplotlib:       2.0.2-py35_2       conda-forge
    mkl:              2017.0.3-0         defaults   
    ncurses:          5.9-10             conda-forge
    numpy:            1.13.1-py35_0      defaults   
    openssl:          1.0.2l-0           conda-forge
    pcre:             8.39-0             conda-forge
    pip:              9.0.1-py35_0       conda-forge
    pyparsing:        2.2.0-py35_0       conda-forge
    pyqt:             5.6.0-py35_4       conda-forge
    python:           3.5.4-0            conda-forge
    python-dateutil:  2.6.1-py35_0       conda-forge
    pytz:             2017.2-py35_0      conda-forge
    qt:               5.6.2-3            conda-forge
    readline:         6.2-0              conda-forge
    setuptools:       36.2.2-py35_0      conda-forge
    sip:              4.18-py35_1        conda-forge
    six:              1.10.0-py35_1      conda-forge
    sqlite:           3.13.0-1           conda-forge
    tk:               8.5.19-2           conda-forge
    tornado:          4.5.1-py35_0       conda-forge
    wheel:            0.29.0-py35_0      conda-forge
    xorg-libxau:      1.0.8-3            conda-forge
    xorg-libxdmcp:    1.1.2-3            conda-forge
    xz:               5.2.2-0            conda-forge
    zlib:             1.2.11-0           conda-forge
```

It seems that you are hitting this on Travis-CI can you point me to the log? Could your config be downgrading to a `numpy` older than `1.9` there after the conda env is created?

**Comment by asmeurer** [comment]
https://travis-ci.org/asmeurer/mypython/jobs/262958041

I'm not doing any other conda stuff. I'm not 100% sure where it coming from, but based on the test, I think it is from importing seaborn. 

The stackoverflow answer seems to imply that the problem comes from matplotlib being built against an older numpy than what is installed.

**Comment by asmeurer** [comment]
Also this is OS X, in case you missed that.

**Comment by ocefpaf** [comment]
> The stackoverflow answer seems to imply that the problem comes from matplotlib being built against an older numpy than what is installed.

The stackoverflow is correct but now I can see that you are getting an warning and not an error.

We are OK to do that with an older `numpy` for build and newer on run, an error should happen only when you do the other way around, see https://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling/18369312#18369312 and https://github.com/numpy/numpy/pull/432/commits/170ed4e33d6196d724dc18ddcd42311c291b4587?diff=split

**Comment by asmeurer** [comment]
Well I suspect a lot of people are going to be seeing these warnings with these packages built how they are. So maybe matplotlib should also silence them if they really are innocuous.

**Comment by ocefpaf** [comment]
Also found this: https://github.com/scipy/scipy/issues/6587#issuecomment-247706436

**Pull request merged**
