### PR TITLE
Cease using pyqt on linux as it is badly linked.

### PR DESCRIPTION
**Pull request by pelson**
As discussed in https://github.com/conda-forge/matplotlib-feedstock/issues/36#issuecomment-232064953.

Ping @tacaswell.

### CODE REVIEW

**Comment by ocefpaf** [comment]
It seems that I am getting old and forgetting things! `Qt` is the default then? I believe ee need to patch the `matplotlibrc`.

```shell
import: 'matplotlib.pyplot'
/opt/conda/envs/_test/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/test-tmp_dir/run_test.py", line 29, in <module>
    import matplotlib.pyplot
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 175, in <module>
    "Matplotlib qt-based backends require an external PyQt4, PyQt5,\n"
ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.
TESTS FAILED: matplotlib-1.5.2-np110py27_6
```

**Comment by ocefpaf** [comment]
Actually no, we need to not applied the patch :smile: 

https://github.com/pelson/matplotlib-feedstock/blob/9f557d4daaf02e8dc0ab57b75c751a05bfedf752/recipe/cfg_qt4agg.patch

**Comment by pelson** [comment]
Thanks @ocefpaf.

**Comment by tacaswell** [comment]
Does this like tk as the only gui toolkit on linux available via conda?

**Comment by tacaswell** [comment]
Not stoked about this long term, but seems reasonable until the pyqt building is sorted out.

**Comment by ocefpaf** [comment]
BTW is the `cfg_qt4agg.patch` needed? I just noticed from your latest commit that the actually `matplolibrc` patch was the `rctmp_pyside.patch`.

**Comment by pelson** [comment]
@msarahan has just suggested that it is something that can be hotfixed on defaults.

**Comment by ccordoba12** [comment]
Please don't do this!! This will introduce a further divergence between defaults and conda-forge, and we have enough of those already :-)

I really don't understand how our packages ended up linked to ICU (I checked and re-checked things with the packages I created, and there's no linking at all with ICU).

Right now me and @mingwandroid are quite busy rebuilding Qt4 to introduce our new Qt5 packages, so please wait us until we upload them.

----

In the meantime, you can take a look at our new Qt4 Linux packages here:

https://anaconda.org/ccordoba12/qt/files

to see if they are linked or not against ICU.

**Comment by ocefpaf** [comment]
@ccordoba12 just tried: `ldd lib/libQtGui.so | grep icu` from the file you pointed above and I got nothing.

BTW I also checked `linux-64-qt-4.8.7-3.tar.bz2` (the version used in https://github.com/conda-forge/matplotlib-feedstock/issues/36#issue-163374341) and got nothing. Not sure if that was hotfixed or if I am looking at the wrong one.

**Comment by jakirkham** [comment]
This was my experience looking at the old `qt` and `pyqt` too, @ocefpaf. I know it must be linked somewhere, but was unable to determine where. 😞

**Comment by mingwandroid** [comment]
`hotfix` refers to hacking metadata usually? To change the output of `ldd`, some of the shared objects or executables must have changed, *or else* the system shared objects have changed. IMHO Qt/icu is a red herring. I am not saying Qt is exonerated here, but we need to find the exact problem.

**Comment by tacaswell** [comment]
It is Qt, I'll report more in ~10 min

**Comment by ccordoba12** [comment]
@ocefpaf, we really haven't done anything to our current Qt packages. So if you're not seeing the ICU linking, then that means they didn't have it in the first place ;-)

**Comment by tacaswell** [comment]
env created via

```
conda create -n mpl_test -c conda-forge matplotlib
```

in the top of the env run

```
find ./ -iname '*.so' | xargs ldd > ldd_output.txt
```

which we can parse via:

```python
import re

lib_header = re.compile(r'^\.')

libs = {}
cur_lib = []
with open('ldd_output.txt', 'r') as fd:
    for ln in fd:
        if lib_header.match(ln):
            cur_lib = []
            libs[ln.strip()] = cur_lib
        else:
            cur_lib.append(ln.strip().rstrip())

for k, v in libs.items():
    filtered = [lb for lb in v if 'icu' in lb.lower()]
    if filtered:
        print(k)
        for f in filtered:
            print(' '*4 + f)

```

which gives:

```
./lib/python2.7/site-packages/PyQt4/QtDeclarative.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtDesigner.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/designer/libqdeclarativeview.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtGui.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtTest.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtHelp.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtWebKit.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/qmltooling/libqmldbg_inspector.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtSql.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/designer/libqwebview.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/imageformats/libqsvg.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtDesignerComponents.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/designer/libpyqt4.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtOpenGL.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtOpenGL.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/graphicssystems/libqtracegraphicssystem.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtScriptTools.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/qmltooling/libqmldbg_tcp.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/imports/Qt/labs/particles/libqmlparticlesplugin.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtDesigner.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/imageformats/libqgif.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtWebKit.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/imageformats/libqtga.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/imports/Qt/labs/shaders/libqmlshadersplugin.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtMultimedia.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/imageformats/libqico.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtDeclarative.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/imageformats/libqtiff.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/script/libqtscriptdbus.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtHelp.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/imageformats/libqmng.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/accessible/libqtaccessiblewidgets.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtSvg.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libfontconfig.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/inputmethods/libqimsw-multi.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/imports/QtWebKit/libqmlwebkitplugin.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/imports/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtMultimedia.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/imports/Qt/labs/gestures/libqmlgesturesplugin.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtSvg.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/python2.7/site-packages/PyQt4/QtScriptTools.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/iconengines/libqsvgicon.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/graphicssystems/libqglgraphicssystem.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/qt4/plugins/imageformats/libqjpeg.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
./lib/libQtGui.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
```

**Comment by tacaswell** [comment]
Sorry, the real culprit is buried in the noise

```
./lib/libfontconfig.so:
    libicui18n.so.56 => not found
    libicuuc.so.56 => not found
    libicudata.so.56 => not found
```

**Comment by tacaswell** [comment]
Pulled as part of font-config build

libxml2:    2.9.3-8  conda-forge

Installed from defaults

libxml2                   2.9.2                         0

installed in broken enviroment (default / conda-forge mix)

libxml2                   2.9.2                         0  

Trying to force the broken enviroment gives

```
15:32 $ conda install -c conda-forge libxml2==2.9.3
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/tcaswell/mc3/envs/mpl_test3:

The following NEW packages will be INSTALLED:

    icu:     56.1-4  conda-forge

The following packages will be UPDATED:

    libxml2: 2.9.2-0             --> 2.9.3-8 conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    python:  3.5.2-1 conda-forge --> 3.5.1-0            
    xz:      5.2.2-0 conda-forge --> 5.0.5-1 conda-forge

Proceed ([y]/n)? 
```

**Comment by ocefpaf** [comment]
I am puzzled... Why `icu` shows up in `./lib/libQtGui.so`?

**Comment by tacaswell** [comment]
@ocefpaf Because it depends on `libfontconfig` and ldd seems to identify all of the links, not just the direct ones.

**Comment by ocefpaf** [comment]
Ah... Thanks @tacaswell! That was the red-est herring we had so far in conda-forge!

@pelson let's update our `xz` pinning now :wink:

**Comment by jakirkham** [comment]
Sorry, I think I missed a few steps along the way. What is the connection between `fontconfig` and `xz`?

**Comment by tacaswell** [comment]
I also did not follow the step to xz.

I am also not clear why fontconfig picked up a icu link.  My guess is that it auto identifies if it has it at build time (which it does due to it being installed for libxml). It should probably explicitly pick up a build and run dependency of icu.

**Comment by ocefpaf** [comment]
> I also did not follow the step to xz.

`libxml2` and `Python` > 2.7 depends on `xz`, but `libxml2` from `defaults` does not use `xz` nor `icu`. So pinning would help us get a more consistent stack. However, that was a joke b/c I already pinned libxml2 to the latest `xz` to prevent some other issues, but b/c `libxml2`from defaults is not pinned it can still get pulled anyways.

**Comment by ccordoba12** [comment]
Why do you want libxml2 to depend on ICU? It's a big dependency for a small library :-)

----

By the way, it's good to know that this is not a problem with our Qt packages :-)

**Comment by ocefpaf** [comment]
> Why do you want libxml2 to depend on ICU? It's a big dependency for a small library :-)

That is a good question. I had a user requesting that some long time but I cannot recall. I guess it was to parse a specific xml document he had... @gillins may know more.

**Comment by ccordoba12** [comment]
Probably something with non-ascii chars :-)

**Comment by ccordoba12** [comment]
So, pinning alone is enough to solve this conflict between defaults and conda-forge?

**Comment by ocefpaf** [comment]
> So, pinning alone is enough to solve this conflict between defaults and conda-forge?

Most of the time it is. The problem here is more complex b/c the dependencies for `libxml2` in `conda-forge` and `defaults` are different. What is weird is that a lower version of `libxml2` is chosen when a higher version with compatible pinning is available, but I did not investigate this to figure out why yet.

**Comment by jakirkham** [comment]
Maybe the solver is trying to wiggle out of a more constrained situation? 😕

**Comment by ccordoba12** [comment]
As part of the SciPy sprints I added Qt4 to conda-forge. Now I need to add PyQt4, and that will solve this issue for good ;-)

**Comment by tacaswell** [comment]
Will it fix it by just removing defaults?

I have become conviced the issue is the solver picking the wrong libxml

**Comment by msarahan** [comment]
I think @tacaswell you're right, but the question is why the solver is picking the wrong libxml.  I thought it was pinning, but we were not able to find anything that pinned libxml2 inappropriately in all of conda-forge's feedstocks.

**Comment by ccordoba12** [comment]
> I have become conviced the issue is the solver picking the wrong libxml

Yes, I also think that's the problem and I don't know how to fix it right now. To overcome it I added a dependency on the `qt` conda-forge package to bring `libxml2` from conda-forge (since the conda-forge version is more recent than the one in defaults).

**Comment by ccordoba12** [comment]
See here:

https://github.com/conda-forge/qt-feedstock/blob/master/recipe/meta.yaml#L53

**Comment by pelson** [comment]
Thank you for your hard work on this @ccordoba12 (and others)! I'm happy to say that I think I can now close this issue. 🎉

**Pull request closed without merging**
