### PR TITLE
REL: update for 1.5.2rc1

### PR DESCRIPTION
**Pull request by tacaswell**
Is self merging these things kosher?

### CODE REVIEW

**Comment by ocefpaf** [comment]
> Is self merging these things kosher?

Most of the time yes. But since this is a `rc` release it would be nice to get @pelson opinion about it.

**Comment by tacaswell** [comment]
Should have done this first thing in the morning US time so it would not be late UK time :disappointed: .

**Comment by ocefpaf** [comment]
BTW I am :+1: on `rc` releases here. People can always go back to the default channel version for stability :wink:

**Comment by tacaswell** [comment]
This should be a pretty safe upgrade.

The more exciting decision will be 2.0.0b1 (planned for next week).

**Comment by tacaswell** [comment]
and people can always force a down grade via `conda install matplotlib=1.5.1`

**Comment by janschulz** [comment]
> People can always go back to the default channel version for stability

I added the conda-forge channel as a default because I thought I do get as stable software as `defaults`, just more of them. :-/

**Comment by ocefpaf** [comment]
> I added the conda-forge channel as a default because I thought I do get as stable software as `defaults`, just more of them. :-/

I do want you to keep that idea in mind :smile:  but I am not opposed to a release candidate every now and then. Bare in mind that merging this PR is just my opinion.

The pro for doing this is to get a larger user base to test the `rc` right away. The con is that we don't want conda-forge to become a CI-like release service for dev versions. (At least not right now and definitely not by publishing the binaries in the `main` channel.)

**Comment by tacaswell** [comment]
Is there a (insert time scale) plan for dev releases?  That is one of the features of conda-forge that I am most excited about.

I definitely want to either use (or adapt) this infrastructure to get lots of user feed back on the 2.0 beta/rcs

**Comment by janschulz** [comment]
@tacaswell https://github.com/conda-forge/conda-forge.github.io/issues/147

I've no idea how this works, but I sure hope that I won't get these prereleases automatically. If you want a fast way to make prereleases available to conda users, my suggestion would be to register a `matplotlib` org on anaconda.org and host the feedstock for prereleases there. 

Steps:
* clone the feedstock repo localy
* add the following to the .conda-forge.yml (assuming the anaconda.org account is `matplotlib`:

```
channels:
  sources: [matplotlib]
  targets:
  - [matplotlib, main]
```

* then do the steps under https://github.com/conda-forge/conda-smithy#making-a-new-feedstock, starting at 2). This requires tokens for all services (anaconda, github, circleci, appveyor):

```
λ ls ~\.conda-smithy\
anaconda.token  appveyor.token  circle.token  github.token
```

**Comment by pelson** [comment]
> Is self merging these things kosher?

Of course. You are [1/4 responsible](https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml#L76) for the matplotlib available on conda-forge. If you mess it up, you have to fix it 😜 

> But since this is a rc release it would be nice to get @pelson opinion about it.

Thanks @ocefpaf. Release candidates are controversial, and I mostly agree with @janschulz on this. However, matplotlib release candidates was one of the main reasons I wrote conda-forge in the first place, so it is fitting that we have reached this stage. As there is a short term deadline on this and the 2.0 rc, I'm going to experiment somewhat (I'm another 1/4 responsible after all 😉 ) and push a dev branch which uploads to the `conda-forge/channels/rc` channel. With this channel I promise *nothing* - binaries on it may very well not exist from week to week (well, at least once the release is out of the door proper) -  we can come up with a conda-forge policy on this which encourages release candidates to be graduated into real releases in X number of weeks. Would be a good one to discuss at a conda-forge hangout.


I'll follow up this comment with commits etc.

**Comment by pelson** [comment]
Ok, so I have pushed a [devel](https://github.com/conda-forge/matplotlib-feedstock/tree/devel) branch which has 3 commits more than master bc4e472, efd97af, 1ba5a79. This will result in `v1.5.2rc1` being available as an opt-in with `conda install -c conda-forge/channel/rc matplotlib`. With distribution being so much easier than ever before, there is a debate to be had on the value vs reproducibility of release candidates versus cycling through release versions quicker, but we can't change the world overnight 😉 .
I'm not keen for this pattern to be rolled out wider at this stage - I'd like for the release candidate discussion to take place on the conda-forge hangout so that we can put together a coherent strategy for doing this kind of thing (even if that means individual packages have to maintain their own CI running "devel" repos). @tacaswell - feel free to merge 2.0rc1 onto the `devel` branch when you see fit.

My main reasons for making this exception are:

 * it gives us insight into how doing RCs in this way would look
 * it allows me to scratch an itch in helping matplotlib do release candidates more easily
 * it gives us some impetus to bring this conversation into a future conda-forge hangout

@jakirkham - I just want you to have some awareness of this.

**Comment by pelson** [comment]
Closing as it was cherry-picked onto devel.

**Pull request closed without merging**
