### PR TITLE
Bump build for newer openblas.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by pelson** [comment]
Closes https://github.com/conda-forge/matplotlib-feedstock/issues/32#issuecomment-228387521.

**Comment by ocefpaf** [comment]
Don't we need https://github.com/conda-forge/numpy-feedstock/pull/16 too?

**Comment by ocefpaf** [comment]
@pelson can we at least delete openblas previous release to ensure that conda won't pull a lower build number? We saw that happen before and it will be a hard thing to debug.

**Comment by pelson** [comment]
> can we at least delete openblas previous release to ensure that conda won't pull a lower build number?

Yes. We should certainly do that. We don't want an openblas being pulled in that has the full libgcc dep stack.

**Comment by ocefpaf** [comment]
> Yes. We should certainly do that. We don't want an openblas being pulled in that has the full libgcc dep stack.

Done. Thank you!

**Pull request merged**
