### PR TITLE
move matplotlib-base content to its output, use noarch where possible

### PR DESCRIPTION
**Pull request by msarahan**
This is a minor cleanup to the recipe that distinguishes the top-level recipe (which does nothing here) from the outputs.  It makes the matplotlib-base part more explicitly an output.

Besides that, I have made the metapackage and the data packages into noarch.  For the data package especially, this might make things more efficient, depending on the use case.

### CODE REVIEW

**Comment by tacaswell** [comment]
This seems sensible to me.  I have not been following conda-build developments enough to comment on the correctness (why is one `noarch: generic` and the other `noarch: python`?).

The travis failures look like the docker containers are broken at the image level?

@conda-forge-admin, please rerender

**Comment by msarahan** [comment]
The pure metapackage can be noarch: generic because it has no files whatsoever, and no actual dependency on python.  The data package can be noarch: python because it appears to contain some python files that need to respect the python filesystem layout.  There's really no much difference - in either case, you get a package that runs on all pythons, and on all OS's.

This might be incorrect as is, though - it may need to add constraints on the noarch-associated python to enforce the minimum python version, but that probably won't actually matter, since there won't be any matplotlib-base builds for py<35

**Comment by ocefpaf** [comment]
Let's give this a try. Thanks @msarahan!

**Comment by ocefpaf** [comment]
@msarahan for some reason installing `matplotlib`, not `matplotlib-base`, is not pulling `pyqt` as it should with this PR. Do you have any ideas why this is happening?

I'll remove the packages created from this but I won't revert it just yet b/c I want to figure out if I can fix it.

**Comment by isuruf** [comment]
>  Do you have any ideas why this is happening?

noarch:generic packages shouldn't have selectors.

**Comment by ocefpaf** [comment]
> noarch:generic packages shouldn't have selectors.

We should make that an error in the linter.

**Pull request merged**
