### PR TITLE
Fix test for `matplotlib-base`

### PR DESCRIPTION
**Pull request by fcollonval**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

As per https://github.com/conda/conda-build/issues/3933, test section for the first subpackage is ignored when the top package as the same name. This fixes it.

### CODE REVIEW

**Comment by fcollonval** [comment]
@conda-forge-admin, please rerender

**Comment by dopplershift** [comment]
You should be able to fix the window builds by borrowing the lines added by @isuruf at the end of #238

**Comment by dopplershift** [comment]
Or if you prefer, I can push those changes to your branch.

**Comment by fcollonval** [comment]
@dopplershift Thanks for the review and suggestion.

**Comment by mattip** [comment]
@isuruf @jakirkham is this needed for windows builds to succeed?

**Pull request closed without merging**
