### PR TITLE
Move skip to individual outputs

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@ericpre and @ocefpaf This fixes the issue with the missing Linux and Mac OS X builds.

**Comment by jan-janssen** [comment]
pypy builds fail for 3.4.0: 

```
    In file included from src/_path_wrapper.cpp:3:
    src/_path.h: In function 'void __add_number(double, char, int, std::string&)':
    src/_path.h:1105:40: error: 'Py_DTSF_ADD_DOT_0' was not declared in this scope
     1105 |           val, format_code, precision, Py_DTSF_ADD_DOT_0, NULL);
          |                                        ^~~~~~~~~~~~~~~~~
    error: command '/home/conda/feedstock_root/build_artifacts/matplotlib-suite_1617008684932/_build_env/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1
    Running setup.py install for matplotlib: finished with status 'error'
```

**Comment by ocefpaf** [comment]
@isuruf and @mattip are you OK merging this without `pypy` for now?

**Comment by tacaswell** [comment]
There is a really nasty bug in mpl340, I would not be mad if CF waited for 3.4.1 before rebuilding!

**Comment by ocefpaf** [comment]
> There is a really nasty bug in mpl340, I would not be mad if CF waited for 3.4.1 before rebuilding!

You are a maintainer here, so you are CF too ;-p

Let's make this one draft and we'll update once 3.4.1 is out.

Should we pull the 3.4.0 that got in when I merged #289?

**Comment by tacaswell** [comment]
We are currently debating if we should yank the pypi package or not on our gitter.  We should do the same here as there.

Bug is https://github.com/matplotlib/matplotlib/issues/19787 , only affects 3D scatters that change color or size.  I expect narrow user base, but catastrophic but silently wrong plots!

> You are a maintainer here, so you are CF too ;-p

fair, but I'm an uninformed small-fish over here :-p

**Comment by ocefpaf** [comment]
> We should do the same here as there.

OK. Let me know what you decide and I'll pull them if we need it.

**Comment by isuruf** [comment]
pypy issue https://foss.heptapod.net/pypy/pypy/-/issues/3424

**Comment by isuruf** [comment]
We could patch matplotlib for now with something like,
```
#ifndef Py_DTSF_ADD_DOT_0
#define Py_DTSF_ADD_DOT_0 0x02
#endif
```

**Comment by QuLogic** [comment]
> Should we pull the 3.4.0 that got in when I merged #289?

I pulled it, as I don't think CI for the changes going into 3.4.1 will be done tonight. Maybe tomorrow or so.

**Comment by jan-janssen** [comment]
For the moment the pypi bug remains in 3.4.1: 
```
    In file included from src/_path_wrapper.cpp:3:
    src/_path.h: In function 'void __add_number(double, char, int, std::string&)':
    src/_path.h:1105:40: error: 'Py_DTSF_ADD_DOT_0' was not declared in this scope
     1105 |           val, format_code, precision, Py_DTSF_ADD_DOT_0, NULL);
          |                                        ^~~~~~~~~~~~~~~~~
```

**Comment by jan-janssen** [comment]
> We could patch matplotlib for now with something like,
> 
> ```
> #ifndef Py_DTSF_ADD_DOT_0
> #define Py_DTSF_ADD_DOT_0 0x02
> #endif
> ```

I followed the suggestion from @isuruf to patch the pypi builds, now the tests seem to pass.

**Pull request merged**
