### PR TITLE
WIP: Attempting to help with v2.0.0rc1

### PR DESCRIPTION
**Pull request by ericdill**
cc @tacaswell

### CODE REVIEW

**Comment by tacaswell** [comment]
Interesting, my attempt to run conda smithy gave me a very different diff....

**Comment by ericdill** [comment]
travis is probably fine, I over-zealously killed it while trying to halt #82

**Comment by ericdill** [comment]
restarting travis-ci now, let's see what happens

**Comment by tacaswell** [comment]
I merged locally to reset the build number to 0.

Thanks @ericdill !

**Comment by ericdill** [comment]
Glad the "do the same thing you did and push to GH" trick worked!

**Comment by ericdill** [comment]
(further proof that having to manage state sucks)

**Comment by jakirkham** [comment]
Thanks for doing this @ericdill .

**Pull request merged**
