### PR TITLE
MNT: Re-rendered with conda-smithy 1.3.2

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/matplotlib-feedstock/issues/73

Includes a build number bump to address issue ( https://github.com/conda-forge/matplotlib-feedstock/issues/73 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
Could someone please take a look at this?

**Comment by jakirkham** [comment]
Also have pulled all packages built within the past 24hrs as they are compromised (built on 10.11 not 10.9). The remain in the channel under the label `broken`.

**Comment by ocefpaf** [comment]
> Also have pulled all packages built within the past 24hrs as they are compromised (built on 10.11 not 10.9). The remain in the channel under the label `broken`.

Why would you remove the Windows and Linux packages?  Aff...

**Comment by jakirkham** [comment]
They are still there just relabeled (hence they can be relabeled again). Because I was having a difficult time sorting through them on the bus. Feel free to adjust as needed. 👍

**Comment by ocefpaf** [comment]
How about you don't do that next time.

**Comment by jakirkham** [comment]
The Windows and Linux packages are back in `main`.

**Pull request merged**
