### PR TITLE
bump

### PR DESCRIPTION
**Pull request by ocefpaf**
Re-building with latest `cairo` and `fontconfig`. Hopefully this fixes https://github.com/conda-forge/staged-recipes/issues/862

---

Edit: re-start https://travis-ci.org/conda-forge/staged-recipes/jobs/139773084 once this is merged to check if it works.

### CODE REVIEW

**Comment by ocefpaf** [comment]
AppVeyor is failing with latest conda-build. @pelson are you merging this as is and wait for the new `conda-build` or do you want to pin to an older version?

**Comment by pelson** [comment]
> Re-building with latest cairo and fontconfig

Should these be pinned? I'm just a little surprised that simply bumping the build number fixes anything.

I'm certainly not against merging this PR, just lacking context to do so myself.

**Comment by pelson** [comment]
```
Package: matplotlib-1.5.1-np110py27_3
source tree in: C:\conda\conda-bld\work\matplotlib-1.5.1
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
 
    https://github.com/conda/conda-build/issues
 
Include the output of the command 'conda info' in your report.
 
 
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 144, in main
    args_func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 385, in args_func
    args.func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 332, in execute
    dirty=args.dirty, activate=args.activate)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 553, in build
    windows.build(m, build_file, dirty=dirty, activate=activate)
  File "C:\conda\lib\site-packages\conda_build\windows.py", line 158, in build
    compiler_vars = msvc_env_cmd(bits=cc.bits, override=m.get_value('build/msvc_compiler', None))
  File "C:\conda\lib\site-packages\conda_build\windows.py", line 102, in msvc_env_cmd
    captured_vars = query_vcvarsall(float(version), arch_selector)
  File "C:\conda\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
ValueError: [u'path', u'include', u'lib']
Command exited with code 1
```

The build failure is weird, though it sounds like you have seen it before @ocefpaf?:

```
patch-2.5.9                |                1          56 KB
    conda-env-2.5.1            |           py27_0          67 KB
    markupsafe-0.23            |           py27_2          25 KB 
    psutil-4.3.0               |           py27_0         223 KB
    pytz-2016.4                |           py27_0         171 KB
    ruamel_yaml-0.11.7         |           py27_0         201 KB
    six-1.10.0                 |           py27_0          16 KB
    clyent-1.2.2               |           py27_0          15 KB
    conda-4.1.3                |           py27_0         243 KB
    jinja2-2.8                 |           py27_1         265 KB
    python-dateutil-2.5.3      |           py27_0         236 KB 
    anaconda-client-1.4.0      |           py27_0         154 KB
    conda-build-1.21.1         |           py27_0         312 KB
    obvious-ci-0.5.2.dev2      |           py27_0          58 KB
```

**Comment by ocefpaf** [comment]
> Should these be pinned?

We are not pinning them at the moment and I am not sure we have too b/c the issue was that `libpng` was not properly pinned in some of `matplotlib`'s dependencies. 

> I'm just a little surprised that simply bumping the build number fixes anything.

I am not sure it will fix but it will get `cairo` and `fontconfig` with the same `libpng` we are using in other places. I don't know about `qt` as that is coming from defaults and it is pinned to:

```
qt 4.8.7 3 linux-64 : fontconfig >=2.11.1, freetype >=2.5.2, libpng 1.6*, openssl 1.0.2*, zlib 1.2.*
```

So that means we can have `libpng` `1.6.21` or `1.6.22` there.

> I'm certainly not against merging this PR, just lacking context to do so myself.

> The build failure is weird, though it sounds like you have seen it before @ocefpaf?:

Yep. And @msarahan is already fixing that in https://github.com/conda/conda-build/pull/1046 I believe.

**Comment by pelson** [comment]
> I am not sure it will fix but it will get cairo and fontconfig with the same libpng we are using in other places

At build time, you mean? In which case I assume you are fixing a problem with the build of matplotlib itself? If so, do we also need to remove distributions from the channel, and which ones?

As I say, feel free to merge this PR - it is certainly not going to do *any* harm and would love it to solve your problem.

**Comment by ocefpaf** [comment]
> At build time, you mean?

Yep.

> As I say, feel free to merge this PR - it is certainly not going to do any harm and would love it to solve your problem.

Let's try. If it solves I will remove the bad builds.

**Pull request merged**
